<?php
    /**
     * @var $this CI_Loader
     */
    echo Component::Sidebar([
        'options' => ['img' => ['path' => 'public/images/logo.jpg', 'url' => ''], 'header' => 'MENU PRINCIPAL'],
        /**
         * This is the menu generated by the application, please do not touch this file manually.
         */
        'items' =>
            [
                ['label' => 'Informes', 'options' => ['icon' => 'fa fa-clipboard'],
                    'items' =>
                        [
                            ['label' => 'Asesoría', 'options' => ['icon' => 'fa fa-th-list'],
                                'items' =>
                                    [
                                        ['label' => 'Enviar asesorías', 'url' => 'informe/enviarasesoriaspractica', 'options' => ['icon' => 'ion-paper-airplane']],
                                        ['label' => 'Asesorías de prácticas', 'url' => 'informe/asesoriapracticas', 'options' => ['icon' => 'fa fa-list-alt']],
                                    ],
                            ],
                        ],
                ],
            ],
    ]);
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">